name: Django CI/CD Pipeline

on:
  push:
    branches:
      - master  # Branche principale
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Étape 3 : Debug - Vérifier les fichiers présents
      - name: List project files
        run: ls -R

      # Étape 4 : Installation des dépendances
      - name: Install dependencies
        run: |
          pip install --upgrade pip  # Met à jour pip
          pip install -r requirements.txt
        working-directory: C:\Users\molka\projet  # Changez ce chemin si nécessaire

      # Étape 5 : Exécuter les tests
      - name: Run tests
        run: |
          python manage.py test
        working-directory: projet_ds1  # Changez ce chemin si nécessaire
