name: Django CI/CD Pipeline

on:
  push:
    branches:
      - master  # ou "master" selon ta configuration de branche

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd projet_ds1  # Assurez-vous de naviguer dans le répertoire correct
          python manage.py test  # Lance les tests dans le répertoire où manage.py est situé
