name: Django CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          cd myprojectds1
          pip install -r requirements.txt

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: |
          cd myprojectds1
          python manage.py test

  deploy:
    needs: test  # Assurez-vous que les tests réussissent avant le déploiement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 1 : Déployer sur Render
      - name: Deploy to Render
        run: |
          curl -sSL https://render.com/deploy/github --data-urlencode "repo=${{ github.repository }}" --data-urlencode "branch=master" --data-urlencode "access_token=${{ secrets.RENDER_ACCESS_TOKEN }}"

